-- Keep all reserved attempts. Old completed checks have unknown application provenance:
-- never infer that their current restaurant amenities were written by this checker.
ALTER TABLE place_amenity_checks DROP CONSTRAINT place_amenity_checks_pkey;
ALTER TABLE place_amenity_checks ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE place_amenity_checks ADD COLUMN mode text NOT NULL DEFAULT 'initial'
  CONSTRAINT place_amenity_checks_mode_check CHECK (mode IN ('initial', 'refresh'));
ALTER TABLE place_amenity_checks ADD COLUMN source text NOT NULL DEFAULT 'google_place_details_new';
ALTER TABLE place_amenity_checks ADD COLUMN observed_amenities text[];
ALTER TABLE place_amenity_checks ADD COLUMN baseline_amenities text[];
ALTER TABLE place_amenity_checks ADD COLUMN applied_at timestamptz;
ALTER TABLE place_amenity_checks ADD COLUMN reviewed_by text;
ALTER TABLE place_amenity_checks ADD COLUMN review_note text;
ALTER TABLE place_amenity_checks ADD COLUMN review_decision text
  CONSTRAINT place_amenity_checks_review_decision_check
  CHECK (review_decision IS NULL OR review_decision IN ('applied', 'rejected', 'conflict'));
CREATE INDEX place_amenity_checks_place_recent_idx ON place_amenity_checks (place_id, id DESC);